function img(name) {
  return `https://raw.githubusercontent.com/jonaslacandola0617/learning-platform/main/public/images/${name}.png`
}

export const puzzles = [
  {
    id: 1,
    image: img('matalino'),
    emoji: "📚",
    emojiLabel: "Batang nag-aaral na may mga libro",
    answer: "MATALINO",
    hint: "Palaging matatalino ang mga batang nagbabasa!",
    description: "Ang batang ito ay laging handa at nagdadala ng mga aklat para sa klase.",
    revealed: [0, 4, 6],
    poolExtra: ["B", "U", "S", "G", "E", "K"],
  },
  {
    id: 2,
    image: img('matulungin'),
    emoji: "🎁",
    emojiLabel: "Mga batang nagbibigay ng donasyon",
    answer: "MATULUNGIN",
    hint: "Ang pagbibigay ay isang magandang katangian!",
    description: "Ang mga batang ito ay nag-aambag ng mga bagay para sa donations box.",
    revealed: [2, 4, 8, 9],
    poolExtra: ["B", "S", "O", "K", "P", "R"],
  },
  {
    id: 3,
    image: img('malikhain'),
    emoji: "🎨",
    emojiLabel: "Mga batang nagpipinta at lumilikha",
    answer: "MALIKHAIN",
    hint: "Gumagawa ng bagong sining at ideya!",
    description: "Ang mga batang ito ay nagpipinta at lumilikha ng magagandang obra.",
    revealed: [1, 4, 5, 8],
    poolExtra: ["T", "S", "B", "O", "U", "R"],
  },
  {
    id: 4,
    image: img('mapanuri'),
    emoji: "🔍",
    emojiLabel: "Batang nagtatanong at nagmamasid",
    answer: "MAPANURI",
    hint: "Mahilig magtanong at mag-obserba!",
    description: "Ang batang ito ay laging nagtatanong at nagmamasid upang matuto pa.",
    revealed: [0, 2, 4, 6],
    poolExtra: ["T", "L", "S", "B", "O", "G"],
  },
  {
    id: 5,
    image: img('masipag'),
    emoji: "🌿",
    emojiLabel: "Mga batang naglilinis ng kalikasan",
    answer: "MASIPAG",
    hint: "Walang pagod sa paggawa para sa kalikasan!",
    description: "Ang mga batang ito ay naglilinis ng kapaligiran.",
    revealed: [2, 4, 6],
    poolExtra: ["T", "L", "N", "O", "B", "U"],
  },
]
