function img(name) {
  return `https://raw.githubusercontent.com/jonaslacandola0617/learning-platform/main/public/images/${name}.png`
}

export const puzzles = [
  {
    id: 1,
    image: img('matalino'),
    emoji: "📚",
    emojiLabel: "A child studying with books",
    answer: "INTELLIGENT",
    hint: "Reading and studying can help you become smarter.",
    description: "This learner is prepared and brings books to class.",
    revealed: [0, 4, 6],
    poolExtra: ["B", "U", "S", "G", "E", "K"],
  },
  {
    id: 2,
    image: img('matulungin'),
    emoji: "🎁",
    emojiLabel: "Children giving donations",
    answer: "HELPFUL",
    hint: "Giving your time or things can help other people.",
    description: "These children are adding useful items to a donation box.",
    revealed: [0, 3, 6],
    poolExtra: ["B", "S", "O", "K", "P", "R"],
  },
  {
    id: 3,
    image: img('malikhain'),
    emoji: "🎨",
    emojiLabel: "Children painting and creating art",
    answer: "CREATIVE",
    hint: "This word describes someone who makes new art and ideas.",
    description: "These children are painting and making original artwork.",
    revealed: [1, 4, 7],
    poolExtra: ["T", "S", "B", "O", "U", "R"],
  },
  {
    id: 4,
    image: img('mapanuri'),
    emoji: "🔍",
    emojiLabel: "A child asking questions and observing",
    answer: "CURIOUS",
    hint: "This person enjoys asking questions and discovering new things.",
    description: "This learner asks questions and observes carefully to learn more.",
    revealed: [0, 3, 6],
    poolExtra: ["T", "L", "S", "B", "O", "G"],
  },
  {
    id: 5,
    image: img('masipag'),
    emoji: "🌿",
    emojiLabel: "Children cleaning their surroundings",
    answer: "HARDWORKING",
    hint: "This person keeps doing their best until the job is finished.",
    description: "These children are working together to clean their surroundings.",
    revealed: [0, 4, 7, 10],
    poolExtra: ["T", "L", "N", "O", "B", "U"],
  },
]
