export const WORD_TOPICS = [
  { id: "animals", label: "Animals", icon: "🐾", description: "Familiar animals from land, sea, and sky" },
  { id: "verbs", label: "Action Words", icon: "🏃", description: "Simple things people can do" },
  { id: "adjectives", label: "Describing Words", icon: "🌈", description: "Words that describe people and things" },
  { id: "objects", label: "Everyday Objects", icon: "🎒", description: "Things found at home or in school" },
  { id: "values", label: "Good Values", icon: "💛", description: "Positive traits and good behavior" },
];

const topicWords = {
  animals: [
    ["ELEPHANT", "I am a huge animal with a long trunk.", "🐘"],
    ["GIRAFFE", "I am very tall and have a long neck.", "🦒"],
    ["PENGUIN", "I am a bird that swims but cannot fly.", "🐧"],
    ["DOLPHIN", "I am a smart sea animal that jumps above water.", "🐬"],
    ["TIGER", "I am a large wild cat with orange and black stripes.", "🐯"],
    ["RABBIT", "I have long ears and love to hop.", "🐰"],
    ["TURTLE", "I move slowly and carry a shell on my back.", "🐢"],
    ["MONKEY", "I like to climb trees and swing from branches.", "🐒"],
    ["ZEBRA", "I look like a horse with black and white stripes.", "🦓"],
    ["KANGAROO", "I jump on strong legs and carry my baby in a pouch.", "🦘"],
    ["OCTOPUS", "I live in the sea and have eight arms.", "🐙"],
    ["BUTTERFLY", "I have colorful wings and begin life as a caterpillar.", "🦋"],
    ["CROCODILE", "I am a large reptile with strong jaws.", "🐊"],
    ["SQUIRREL", "I climb trees and collect nuts.", "🐿️"],
    ["FLAMINGO", "I am a pink bird that often stands on one leg.", "🦩"],
  ],
  verbs: [
    ["JUMP", "Push yourself off the ground with both feet.", "🤸"],
    ["RUN", "Move quickly using your legs.", "🏃"],
    ["SWIM", "Move through water using your arms and legs.", "🏊"],
    ["READ", "Look at written words and understand them.", "📖"],
    ["WRITE", "Use letters to put ideas on paper.", "✍️"],
    ["SING", "Make music using your voice.", "🎤"],
    ["DANCE", "Move your body to music.", "💃"],
    ["CLIMB", "Move upward using your hands and feet.", "🧗"],
    ["COOK", "Prepare food using heat.", "🧑‍🍳"],
    ["DRAW", "Create a picture using a pencil or pen.", "🎨"],
    ["LAUGH", "Make a happy sound when something is funny.", "😂"],
    ["SLEEP", "Rest with your eyes closed.", "😴"],
    ["THROW", "Send something through the air with your hand.", "🥎"],
    ["CATCH", "Stop and hold something moving toward you.", "👐"],
    ["BUILD", "Put parts together to make something.", "🧱"],
  ],
  adjectives: [
    ["HAPPY", "Feeling cheerful and pleased.", "😊"],
    ["BRAVE", "Ready to face something difficult or scary.", "🦁"],
    ["GENTLE", "Calm, kind, and careful.", "🕊️"],
    ["BRIGHT", "Giving off lots of light.", "☀️"],
    ["QUICK", "Moving or happening fast.", "⚡"],
    ["SLOW", "Moving without much speed.", "🐌"],
    ["TALL", "Having greater height than usual.", "🌴"],
    ["SMALL", "Little in size.", "🐜"],
    ["QUIET", "Making very little sound.", "🤫"],
    ["LOUD", "Making a strong sound.", "📢"],
    ["SOFT", "Smooth and pleasant to touch.", "🧸"],
    ["STRONG", "Able to lift or carry heavy things.", "💪"],
    ["KIND", "Friendly and caring toward others.", "💛"],
    ["CLEAN", "Free from dirt or mess.", "✨"],
    ["FUNNY", "Making people laugh.", "😄"],
  ],
  objects: [
    ["PENCIL", "You use me to write and can erase my marks.", "✏️"],
    ["CHAIR", "You sit on me.", "🪑"],
    ["TABLE", "You place food, books, or other things on me.", "🪵"],
    ["BOTTLE", "I hold water or another drink.", "🍼"],
    ["CLOCK", "I show you the time.", "🕐"],
    ["UMBRELLA", "I help keep you dry in the rain.", "☂️"],
    ["BACKPACK", "You carry books and school supplies inside me.", "🎒"],
    ["CAMERA", "You use me to take pictures.", "📷"],
    ["SPOON", "You use me to eat soup or cereal.", "🥄"],
    ["PILLOW", "You rest your head on me in bed.", "🛏️"],
    ["LAMP", "I give light inside a room.", "💡"],
    ["KEYBOARD", "You press my keys to type on a computer.", "⌨️"],
    ["SCISSORS", "I have two blades and cut paper.", "✂️"],
    ["BASKET", "You can carry or store things inside me.", "🧺"],
    ["WINDOW", "You can look through me to see outside.", "🪟"],
  ],
  values: [
    ["KIND", "You care about others and treat them well.", "💛"],
    ["HONEST", "You tell the truth even when it is difficult.", "🤝"],
    ["HELPFUL", "You are ready to assist someone who needs you.", "🙌"],
    ["PATIENT", "You can wait calmly without getting upset.", "⏳"],
    ["POLITE", "You use good manners when speaking and acting.", "🙏"],
    ["CARING", "You show concern for people, animals, and nature.", "🌱"],
    ["BRAVE", "You face challenges even when you feel afraid.", "🦁"],
    ["FAIR", "You treat people equally and follow the rules.", "⚖️"],
    ["FRIENDLY", "You make others feel welcome.", "👋"],
    ["RESPECTFUL", "You value other people and their feelings.", "🌻"],
    ["GENEROUS", "You are happy to share with others.", "🎁"],
    ["RESPONSIBLE", "You do what you promised and care for your duties.", "✅"],
    ["GRATEFUL", "You notice and appreciate the good things you receive.", "🌟"],
    ["THOUGHTFUL", "You think about how your actions affect others.", "💭"],
    ["HARDWORKING", "You keep doing your best until the job is done.", "💪"],
  ],
};

export function getBuiltInWords(topicId, count, randomize = false) {
  const source = topicWords[topicId] || topicWords.animals;
  const ordered = randomize
    ? [...source].sort(() => Math.random() - 0.5)
    : source;

  return ordered.slice(0, count).map(([answer, hint, emoji]) => ({
    answer,
    hint,
    emoji,
    emojiLabel: `${answer.toLocaleLowerCase("en-US")} illustration`,
    description: `Which word from ${WORD_TOPICS.find((topic) => topic.id === topicId)?.label || "this topic"} matches this clue?`,
    topic: topicId,
  }));
}
